# Generated by Django 3.2.5 on 2021-09-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_contact_registerr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_us',
            new_name='Contact_no',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messages',
        ),
    ]
